chunks-cache:
    enabled: true
index-cache:
    enabled: true
metadata-cache:
    enabled: true
results-cache:
    enabled: true
minio:
    enabled: false
nginx:
    enabled: false
rbac:
    create: false
    pspEnabled: false
serviceAccount:
    create: false

# To be updated in https://github.com/grafana/mimir/issues/2922
rollout_operator:
  enabled: false
ingester:
  zoneAwareReplication:
    enabled: false
store_gateway:
  zoneAwareReplication:
    enabled: false

# Used to compute GOMEMLIMIT and GOMAXPROCS. These request values are used in Jsonnet.
distributor:
  resources:
    requests:
      cpu: 2
      memory: 2Gi
