{{- if and (not .Values.enterprise.enabled) .Values.nginx.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mimir.resourceName" (dict "ctx" . "component" "nginx") }}
  labels:
    {{- include "mimir.labels" (dict "ctx" . "component" "nginx") | nindent 4 }}
  namespace: {{ .Release.Namespace | quote }}
data:
  nginx.conf: |
    {{- tpl .Values.nginx.nginxConfig.file . | nindent 4 }}
{{- end -}}
