apiVersion: 1
datasources:
- name: Mimir
  type: prometheus
  access: proxy
  uid: mimir
  orgID: 1
  url: http://mimir-1:8001/prometheus
  isDefault: false
  jsonData:
    prometheusType: Mimir
    exemplarTraceIdDestinations:
    - name: traceID
      datasourceUid: jaeger
- name: Jaeger
  type: jaeger
  access: proxy
  uid: jaeger
  orgID: 1
  url: http://jaeger:16686/

- name: phlare
  type: phlare
  access: proxy
  uid: phlare
  basicAuth: false
  editable: true
  isDefault: true
  url: http://phlare:4100
  version: 1