apiVersion: 1
datasources:
- name: Mimir
  type: prometheus
  access: proxy
  uid: mimir
  orgID: 1
  url: http://nginx:8080/prometheus
  isDefault: true
  jsonData:
    prometheusType: Mimir
    exemplarTraceIdDestinations:
    - name: traceID
      datasourceUid: jaeger

- name: Jaeger
  type: jaeger
  access: proxy
  uid: jaeger
  orgID: 1
  url: http://jaeger:16686/

- name: Mimir (load testing query path for standard engine)
  type: prometheus
  access: proxy
  uid: mimir-standard
  orgID: 1
  url: http://query-frontend-standard:8207/prometheus
  jsonData:
    prometheusType: Mimir
    exemplarTraceIdDestinations:
      - name: traceID
        datasourceUid: jaeger

- name: Mimir (load testing query path for streaming engine)
  type: prometheus
  access: proxy
  uid: mimir-streaming
  orgID: 1
  url: http://query-frontend-streaming:8307/prometheus
  jsonData:
    prometheusType: Mimir
    exemplarTraceIdDestinations:
      - name: traceID
        datasourceUid: jaeger

- name: Mimir querier (load testing query path for standard engine)
  type: prometheus
  access: proxy
  uid: mimir-querier-standard
  orgID: 1
  url: http://querier-standard:8204/prometheus
  jsonData:
    prometheusType: Mimir
    exemplarTraceIdDestinations:
      - name: traceID
        datasourceUid: jaeger

- name: Mimir querier (load testing query path for streaming engine)
  type: prometheus
  access: proxy
  uid: mimir-querier-streaming
  orgID: 1
  url: http://querier-streaming:8304/prometheus
  jsonData:
    prometheusType: Mimir
    exemplarTraceIdDestinations:
      - name: traceID
        datasourceUid: jaeger
