apiVersion: 1
datasources:
- name: Mimir
  type: prometheus
  access: proxy
  uid: mimir
  orgID: 1
  url: http://nginx:8080/prometheus
  isDefault: true
  jsonData:
    prometheusType: Mimir
    exemplarTraceIdDestinations:
    - name: traceID
      datasourceUid: jaeger
- name: Jaeger
  type: jaeger
  access: proxy
  uid: jaeger
  orgID: 1
  url: http://jaeger:16686/
- name: Mimir (non-streaming)
  type: prometheus
  access: proxy
  uid: mimir-non-streaming
  orgID: 1
  url: http://query-frontend:8007/prometheus
  jsonData:
    prometheusType: Mimir
    exemplarTraceIdDestinations:
      - name: traceID
        datasourceUid: jaeger
- name: Mimir (streaming)
  type: prometheus
  access: proxy
  uid: mimir-streaming
  orgID: 1
  url: http://query-frontend-streaming:8207/prometheus
  jsonData:
    prometheusType: Mimir
    exemplarTraceIdDestinations:
      - name: traceID
        datasourceUid: jaeger
- name: Mimir querier (streaming)
  type: prometheus
  access: proxy
  uid: mimir-querier-streaming
  orgID: 1
  url: http://querier-streaming:8204/prometheus
  jsonData:
    prometheusType: Mimir
    exemplarTraceIdDestinations:
      - name: traceID
        datasourceUid: jaeger
